version: 0.2

phases:
  install:
    # --- YEH WALA SECTION CHANGE HOGA ---
    # 'install:' se 2 spaces extra indent
    runtime-versions:
      # 'runtime-versions:' se 2 spaces extra indent
      nodejs: 20 # Node.js version 20 (LTS).
    # 'install:' se 2 spaces extra indent (same level as runtime-versions:)
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
    # --- END SECTION ---

  build:
    commands:
      - echo "Building React/Vite application for production..."
      - npm run build
      - echo "Build completed." # A good practice to confirm build is finished

  post_build:
    commands:
      - echo "Verifying build output..."
      - ls -al dist

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes