version: 0.2


phases:
  install:
    # --- YEH WALA SECTION CHANGE HOGA ---
    # runtime-versions 'install' phase ka direct child hai, aur commands bhi.
    runtime-versions:
      nodejs: 20 # Node.js version 20 (LTS).
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
    # --- END SECTION ---

  build:
    commands:
      - echo "Building React/Vite application for production..."
      - npm run build 
      - echo "Build completed."

  post_build:
    commands:
      - echo "Verifying build output..."
      - ls -al dist 

artifacts:
  files:
    - '**/*' 
  base-directory: 'dist'
  discard-paths: yes 